### ISSUE TITLE
wrongly assumes empty string is not a key

### ISSUE THREAD

**Issue by kapouer** [Irrelon/irrelon-path#3]
It is perfectly okay to use an empty string for a key.
```
var jsonPath = require('@irrelon/path');
assert.deepEqual(jsonPath.set({}, 'toto.test', 1), {toto: {test: 1}});
assert.deepEqual(jsonPath.set({}, 'toto.', 2), {toto: {"": 2}});
```

**Comment by kapouer** [comment]
I suppose the culprits are:
https://github.com/Irrelon/irrelon-path/blob/a1892238e230be55d7804e4cfae800f5a9e3c26d/dist/Path.js#L366
https://github.com/Irrelon/irrelon-path/blob/a1892238e230be55d7804e4cfae800f5a9e3c26d/dist/Path.js#L300

**Comment by Irrelon** [comment]
Irrelon Path started its life as a dot-notation parser for use in a MongoDB-like database before it broke out into a fully fledged project of its own. That legacy means that support for blank string literals in a path was never considered because the database doesn't support storing data without a path or key name.

I can't see anything immediately "wrong" with allowing this, but it is raising my eyebrow since I can't think of any practical use.

**Comment by Irrelon** [comment]
A PR has been raised against this. Comments and discussion will continue there. https://github.com/Irrelon/irrelon-path/pull/5
